import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Clipboard-backed insertion, bound to the app/field where dictation began.
@MainActor
enum TextInserter {
    struct Target {
        let processID: pid_t
        let element: AXUIElement?
    }

    enum Result: Equatable {
        case inserted
        case copied(String)
    }

    /// Injected in tests so no real clipboard, keyboard or focused app is touched.
    struct Environment {
        var isTrusted: () -> Bool
        var targetUnchanged: () -> Bool
        var waitForModifiers: () async throws -> Bool
        var postPaste: () -> Bool
        var waitForPaste: () async throws -> Void
    }

    static var isTrusted: Bool { AXIsProcessTrusted() }

    static func requestTrust() {
        AXIsProcessTrustedWithOptions(["AXTrustedCheckOptionPrompt" as CFString: true] as CFDictionary)
    }

    static func captureTarget() -> Target? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return Target(processID: app.processIdentifier, element: isTrusted ? focusedElement() : nil)
    }

    static func insert(_ text: String, target: Target?) async throws -> Result {
        try await insert(text, pasteboard: .general, environment: Environment(
            isTrusted: { isTrusted },
            targetUnchanged: { matches(target) },
            waitForModifiers: waitForModifiersReleased,
            postPaste: postCommandV,
            waitForPaste: { try await Task.sleep(for: .milliseconds(400)) }
        ))
    }

    static func insert(_ text: String, pasteboard: NSPasteboard, environment: Environment) async throws -> Result {
        try Task.checkCancellation()
        guard environment.isTrusted() else {
            copy(text, to: pasteboard)
            return .copied("In Zwischenablage – zum Einfügen Bedienungshilfen erlauben")
        }
        // Wait before modifying the clipboard. Anything copied while the user
        // releases the hotkey is now included in the snapshot and preserved.
        let released = try await environment.waitForModifiers()
        try Task.checkCancellation()
        guard released else {
            copy(text, to: pasteboard)
            return .copied("In Zwischenablage – Sondertasten loslassen und mit ⌘V einfügen")
        }
        guard environment.targetUnchanged() else {
            copy(text, to: pasteboard)
            return .copied("Textfeld gewechselt – Diktat mit ⌘V einfügen")
        }

        let saved = snapshot(pasteboard)
        copy(text, to: pasteboard)
        let ours = pasteboard.changeCount
        guard environment.postPaste() else {
            return .copied("In Zwischenablage – Diktat mit ⌘V einfügen")
        }

        // Restoration also runs on cancellation, including an originally empty
        // clipboard. A new copy by the user always wins over our snapshot.
        defer {
            if pasteboard.changeCount == ours {
                pasteboard.clearContents()
                if !saved.isEmpty { pasteboard.writeObjects(saved) }
            }
        }
        try await environment.waitForPaste()
        return .inserted
    }

    private static func copy(_ text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        pasteboard.writeObjects([item])
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func matches(_ target: Target?) -> Bool {
        guard let target,
              NSWorkspace.shared.frontmostApplication?.processIdentifier == target.processID else { return false }
        // Some apps expose no AX field; keep the existing paste support for
        // them, but still prevent insertion into a different application.
        guard let original = target.element else { return true }
        guard let current = focusedElement() else { return false }
        return CFEqual(original, current)
    }

    private static func focusedElement() -> AXUIElement? {
        let system = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(system, 0.15)
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value, CFGetTypeID(value) == AXUIElementGetTypeID() else { return nil }
        return (value as! AXUIElement)
    }

    private static func waitForModifiersReleased() async throws -> Bool {
        let held: CGEventFlags = [.maskAlternate, .maskShift, .maskControl, .maskCommand]
        for _ in 0..<40 {
            if CGEventSource.flagsState(.combinedSessionState).intersection(held).isEmpty { return true }
            try await Task.sleep(for: .milliseconds(25))
        }
        return false
    }

    private static func postCommandV() -> Bool {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false) else { return false }
        for event in [down, up] {
            event.flags = .maskCommand
            event.post(tap: .cghidEventTap)
        }
        return true
    }
}
