import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Puts text into the focused text field of whatever app is in front:
/// clipboard + a synthetic ⌘V, then the previous clipboard comes back.
/// Pasting is instant and keyboard-layout independent, unlike typing
/// character by character.
@MainActor
enum TextInserter {
    static var isTrusted: Bool { AXIsProcessTrusted() }

    /// Shows the system prompt that leads to Settings → Accessibility.
    static func requestTrust() {
        let key = "AXTrustedCheckOptionPrompt" as CFString
        AXIsProcessTrustedWithOptions([key: true] as CFDictionary)
    }

    /// Returns false when the text could only be copied (no Accessibility
    /// permission yet) — it is then on the clipboard for a manual ⌘V.
    static func insert(_ text: String) async -> Bool {
        let pasteboard = NSPasteboard.general
        let saved = snapshot(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // Ask clipboard managers (nspasteboard.org convention) not to keep it.
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        pasteboard.writeObjects([item])

        guard isTrusted else { return false }
        let ours = pasteboard.changeCount

        await waitForModifiersReleased()
        postCommandV()

        // Give the target app time to read the clipboard before restoring it.
        try? await Task.sleep(for: .milliseconds(400))
        if pasteboard.changeCount == ours, !saved.isEmpty {
            pasteboard.clearContents()
            pasteboard.writeObjects(saved)
        }
        return true
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    /// A still-held ⌥ or ⇧ from the hotkey would turn ⌘V into another command.
    private static func waitForModifiersReleased() async {
        let held: CGEventFlags = [.maskAlternate, .maskShift, .maskControl, .maskCommand]
        for _ in 0..<40 {
            if CGEventSource.flagsState(.combinedSessionState).intersection(held).isEmpty { return }
            try? await Task.sleep(for: .milliseconds(25))
        }
    }

    private static func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        for down in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: down)
            event?.flags = .maskCommand
            event?.post(tap: .cghidEventTap)
        }
    }
}
